{
    "docs": "https://docs.ansible.com/ansible-core/2.14/dev_guide/testing/sanity/import.html", 
    "results": [
        {
            "message": "The test `ansible-test sanity --test import --python 3.6` [[explain](https://docs.ansible.com/ansible-core/2.14/dev_guide/testing/sanity/import.html)] failed with 3 errors:", 
            "output": "plugins/module_utils/librenms_api_client.py:5:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/libre_devices.py:178:0: traceback: ModuleNotFoundError: No module named 'requests' (at plugins/module_utils/librenms_api_client.py:5:0)\nplugins/modules/libre_devices_info.py:80:0: traceback: ModuleNotFoundError: No module named 'requests' (at plugins/module_utils/librenms_api_client.py:5:0)"
        }
    ], 
    "verified": false
}
